class Variables:
    IMAGE_SIZE = (1200, 1000)
    BRIGHTNESS_STEP = 50
    CELLPOSE_DIAMETER = 30
    ZOOM_STEP = 0.05
    ALPHA = 0.5
    ORIGINAL_ZOOM_FACTOR = 1
    DEFAULT_ZOOM_POSITION = 'center'
    DEFAULT_BRIGHTNESS_LEVEL = 0
    ZOOM_THRESHOLD = 1.5
    RED_BGR = [0, 0, 255]
    URL = 'http://localhost:11434/api/chat'